"""
intake/whatsapp_parser.py

Parses officially EXPORTED chat files (.txt) that an investigator obtains
directly from the messaging app itself:

    WhatsApp:  Chat > ⋮ (menu) > More > Export chat  -> "<chat name>.txt"
    Telegram:  Chat > ⋮ (menu) > Export chat history -> .txt / .json

This is the legally clean way to bring chat content into the case file:
the export is generated by the app under the phone owner's own action
(or the investigator's, if they have lawful access to unlock the phone),
not by bypassing app sandboxing or decrypting a private database.

WhatsApp export line format (most common, no media):
    12/08/24, 10:32 PM - Rahul Kumar: Where are you right now?
    12/08/24, 10:33 PM - Rahul Kumar: <Media omitted>

Telegram .txt export format varies by client version; a best-effort
generic parser is included below.
"""

from __future__ import annotations

import re
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List

# Matches: "12/08/24, 10:32 PM - Sender Name: message text"
# Also handles 24-hr time and both '-' and en-dash separators.
WHATSAPP_LINE_RE = re.compile(
    r"^(?P<date>\d{1,2}/\d{1,2}/\d{2,4}),?\s+"
    r"(?P<time>\d{1,2}:\d{2}(?:\s?[APap][Mm])?)\s*[-–]\s*"
    r"(?P<sender>[^:]+):\s*(?P<message>.*)$"
)

# Matches Telegram's common exported-txt line style:
# "[12.08.2024 22:32:10] Rahul Kumar: message text"
TELEGRAM_LINE_RE = re.compile(
    r"^\[(?P<date>\d{1,2}\.\d{1,2}\.\d{2,4})\s+(?P<time>\d{1,2}:\d{2}(?::\d{2})?)\]\s*"
    r"(?P<sender>[^:]+):\s*(?P<message>.*)$"
)


def parse_chat_export(file_path: Path, platform: str = "whatsapp") -> List[Dict[str, str]]:
    """Parses an exported chat .txt file into structured message records.

    Args:
        file_path: path to the exported .txt file.
        platform: "whatsapp" or "telegram" (selects the line-format regex).

    Returns:
        List of dicts: {"timestamp", "sender", "message", "platform"}
        Multi-line messages are merged into the preceding message.
    """
    pattern = TELEGRAM_LINE_RE if platform == "telegram" else WHATSAPP_LINE_RE
    messages: List[Dict[str, str]] = []

    with open(file_path, "r", encoding="utf-8", errors="ignore") as f:
        for raw_line in f:
            line = raw_line.rstrip("\n")
            if not line.strip():
                continue
            match = pattern.match(line)
            if match:
                gd = match.groupdict()
                messages.append(
                    {
                        "timestamp": f"{gd['date']} {gd['time']}",
                        "sender": gd["sender"].strip(),
                        "message": gd["message"].strip(),
                        "platform": platform,
                    }
                )
            else:
                # Continuation of a multi-line message (e.g. a long text
                # message that wraps to the next line in the export file).
                if messages:
                    messages[-1]["message"] += "\n" + line.strip()
                # else: stray header/system line at file start -> ignore

    return messages


def chat_to_raw_text(messages: List[Dict[str, str]], chat_label: str = "") -> str:
    """Flattens parsed chat messages back into a single plain-text blob
    suitable for state["raw_texts"], preserving timestamp/sender context
    so downstream agents (entities, timeline, contradictions) can use it.
    """
    header = f"--- Chat Export: {chat_label} ---\n" if chat_label else ""
    lines = [
        f"[{m['timestamp']}] {m['sender']}: {m['message']}"
        for m in messages
    ]
    return header + "\n".join(lines)


def detect_platform(file_path: Path) -> str:
    """Best-effort guess of which platform a raw export file came from,
    based on filename and first few lines. Defaults to 'whatsapp'.
    """
    name = file_path.name.lower()
    if "telegram" in name:
        return "telegram"
    if "whatsapp" in name or "chat" in name:
        return "whatsapp"

    try:
        with open(file_path, "r", encoding="utf-8", errors="ignore") as f:
            sample = "".join(next(f) for _ in range(5))
        if TELEGRAM_LINE_RE.match(sample.splitlines()[0] if sample else ""):
            return "telegram"
    except StopIteration:
        pass
    except Exception:
        pass

    return "whatsapp"