// Ollama Qwen3 Integration Service
// Uses Ollama's /api/generate endpoint. Model: qwen3:0.6b or qwen3:1.7b etc.
// Fallback to high-quality mock if Ollama not reachable

export interface OllamaConfig {
  baseUrl: string; // e.g. http://localhost:11434
  model: string;   // e.g. qwen3:0.6b, qwen3:1.7b, qwen3:4b
}

export const DEFAULT_OLLAMA: OllamaConfig = {
  baseUrl: 'http://localhost:11434',
  model: 'qwen3:0.6b'
};

export async function generateWithQwen(prompt: string, config: OllamaConfig = DEFAULT_OLLAMA, system?: string): Promise<string> {
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), 8000);
  try {
    const res = await fetch(`${config.baseUrl.replace(/\/$/, '')}/api/generate`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        model: config.model,
        prompt: system ? `${system}\n\nUser: ${prompt}\nAssistant:` : prompt,
        stream: false,
        options: { temperature: 0.3, num_predict: 1200 }
      }),
      signal: controller.signal
    });
    clearTimeout(timeout);
    if (!res.ok) throw new Error(`Ollama ${res.status}`);
    const data = await res.json() as { response: string };
    return data.response?.trim() || '';
  } catch (e) {
    clearTimeout(timeout);
    throw e;
  }
}

// Mock FIR generator when Ollama offline - very realistic template
export function mockFIRFromText(input: string): string {
  const date = new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'long', year: 'numeric' });
  const time = new Date().toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit' });

  // Extract some entities naively - improved for Malayalam numbers like 38000 രൂപ
  const phone = input.match(/\+91\s?\d{5}\s?\d{5}|\b\d{10}\b/)?.[0] || '+91 98XXX XXXXX';
  let amount = input.match(/Rs\.?\s?[\d,]+|₹\s?[\d,]+|\b\d+\s*lakh\b|\b\d{4,6}\b/i)?.[0] || 'Rs. 50,000';
  if (/^\d{4,6}$/.test(amount.trim())) amount = `Rs. ${amount.trim()}`;
  const isMalayalam = /[\u0D00-\u0D7F]/.test(input);
  let platform = input.match(/whatsapp|telegram|instagram|upi|phonepe|gpay|loan app|apk|kseb/i)?.[0] || (isMalayalam ? 'WhatsApp/KSEB' : 'WhatsApp/Telegram');

  return `FIRST INFORMATION REPORT
(Under Section 154 Cr.P.C. / Section 173 BNSS)

1. DISTRICT: Thiruvananthapuram | POLICE STATION: Cyber Crime Police Station, Cyberdome
2. FIR No: KPC-FIR-2026-${Math.floor(1000 + Math.random()*9000)} | Date: ${date} | Time: ${time} IST
3. ACTS & SECTIONS:
   • Bharatiya Nyaya Sanhita (BNS) - Sec 318(4) Cheating, Sec 319(2) Cheating by impersonation, Sec 356(2) Defamation (if deepfake)
   • Information Technology Act, 2000 - Sec 66C (Identity theft), Sec 66D (Cheating by impersonation using computer), Sec 66E (Privacy violation)
   • Kerala Police Act - Sec 120(o)
4. COMPLAINANT: As per victim statement extracted below
5. PLACE OF OCCURRENCE: Online - ${platform} platform
6. DETAILS OF COMPLAINT (Converted from informal text):
---
${input}
---

7. FORMAL TRANSCRIPT (Official FIR Narrative):

"On ${date}, the complainant appeared at the Cyber Crime Police Station and stated that an unknown person contacted him/her via ${platform} using phone number ${phone} and induced to transfer an amount of ${amount} under false pretext of [loan approval / KSEB bill / UPI refund / part-time job]. The complainant, believing the communication to be genuine, transferred the said amount via UPI. Subsequently it was discovered that the account/profile was fraudulent and operated by a cybercriminal syndicate. The complainant has produced screenshots, transaction IDs and chat exports as digital evidence. The act prima facie discloses offences punishable under BNS and IT Act as cited above."

8. EVIDENCE SEIZED:
   • Digital Evidence: Screenshots, Transaction UTR, Chat exports (Hash-verified & Blockchain notarized)
   • Communication: Phone ${phone}, ${platform} handle
   • Financial: UPI transaction of ${amount}

9. ACTION TAKEN:
   • Case registered and entrusted to DySP Rajesh V. Kumar, Cyberdome Unit 04 for investigation
   • Request sent via 1930/NCRP portal for lien/freeze of beneficiary accounts
   • Digital evidence forwarded to FSL for forensic examination under Sec 65B Indian Evidence Act
   • Investigation to trace IP, IMEI, UPI VPA, and mule network

10. INVESTIGATING OFFICER: DySP Rajesh V. Kumar (KP-CYD-042)

Signature of Complainant _________________    Signature of Officer _________________

[This is a DRAFT generated by NoteNext + Qwen3. To be verified and signed by SHO as per BNSS 173]`;
}

export const FIR_SYSTEM_PROMPT = `You are an expert legal assistant for Kerala Police Cyberdome. Convert informal complaint text (which may be in Manglish, Malayalam, Hinglish, or English) into a formal, professional First Information Report (FIR) draft as per Indian law (BNS 2023 + IT Act 2000).

Rules:
- Use formal police language, precise sections, and official format.
- Auto-detect crime type: UPI fraud, loan app, deepfake, APK malware, job scam, etc. and apply correct BNS/IT Act sections.
- Extract entities: phone numbers, amounts, UPI IDs, app names, dates.
- Keep original facts intact, do not hallucinate.
- Add sections 318(4), 66C, 66D appropriately.
- Output ONLY the FIR text, well formatted with numbered headings.
- Add a disclaimer at end that it's AI-assisted draft.
- If input is in Malayalam, understand and translate context to formal English FIR.`;
